config/routes.rb
Rails.application.routes.draw do

  resources :pethomes do
    resources :pets, only: [ :create ]

    resources :bookings, only: [ :create, :udapte, :show, :destroy]

  end
  root to: 'pethomes#index'


  devise_for :users

  patch 'bookings/:id/approve', to: "bookings#approve_booking", as: :booking_approve
  get 'account', to: 'users#show'
  get '/search', to: 'pethomes#search', as: :pethomes_search
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  before_create :set_default
  belongs_to :user
  belongs_to :pethome
  has_many :pethome_reviews
  has_many :petsitter_reviews

  def set_default
    self.status ||= "pending"
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :pethome
  mount_uploader :photo, PhotoUploader

  def self.default_url
    "https://i.ytimg.com/vi/SfLV8hD7zX4/maxresdefault.jpg"
  end
end

app/models/pethome.rb
class Pethome < ApplicationRecord
  belongs_to :user
  has_many :pets
  has_many :bookings
  has_many :pethome_reviews, through: :bookings

  mount_uploader :photo, PhotoUploader

  def self.search(search)
    where("address ILIKE ?", "%#{search}%")
  end

end

app/models/pethome_review.rb
class PethomeReview < ApplicationRecord
  belongs_to :booking
  validates :rating, :inclusion => { :in => 0..5 }
end

app/models/petsitter_review.rb
class PetsitterReview < ApplicationRecord
  belongs_to :booking
  validates :rating, :inclusion => { :in => 0..5 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pethomes
  has_many :bookings
  has_many :petsitter_reviews, through: :bookings
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_pethome, only: [:create]

  def create
    @booking = Booking.new(booking_params)
    @booking.pethome = @pethome
    @booking.user = current_user
    @booking.save
    redirect_to account_path, notice: "Thanks for your booking. Details are saved on your profile"
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(params[:booking])

  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
  end

  def approve_booking
    @booking = Booking.find(params[:id])
    @booking.status = "approved"
    @booking.save
    redirect_to account_path, notice: "A booking from #{@booking.user_id} has been accepted"
  end

  private

  def set_pethome
    @pethome = Pethome.find(params[:pethome_id])

  end

  def booking_params
    params.require(:booking).permit(:pethome, :user, :pethome_reviews, :booking_reviews, :status, :starting_date, :ending_date)
  end

end

app/controllers/pethomes_controller.rb
class PethomesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @pethomes = Pethome.all
  end

  def new
    @pethome = Pethome.new  # GET /pethomes/new
  end

  def create # POST /pethomes
    @pethome = Pethome.new(pethome_params)
    @pethome.user = current_user
    @pethome.save
    redirect_to pethomes_path
  end

  def search
    @pethomes = Pethome.all

    if params[:search] && params[:search] != ''
      @pethomes = Pethome.search(params[:search]).order("created_at DESC")
    end

  end

  def show  # GET /pethomes/:idS
    @pethome = Pethome.find(params[:id])
    @pet = Pet.new
  end

  def edit # GET /pethomes/:id/edit
    if @pethome.user != current_user
      redirect_to route_path, notice: "You are not authorized to edit this page"
    end
    @pethome = Pethome.find(params[:id])
  end

  def update
    @pethome = Pethome.find(params[:id])
    if @pethome.update(pethome_params)
      redirect_to pethomes_path
    else
      render :edit
    end
  end

  private

  def pethome_params
    params.require(:pethome).permit(:bookings, :pets, :pethome_reviews, :address, :bedrooms, :guests, :observations, :photo, :photo_cache)
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def create
    @pet = Pet.new(pet_params)
    @pethome = Pethome.find(params[:pethome_id])
    @pet.pethome = @pethome
    @pet.save
    redirect_to @pethome
  end


private
  def pet_params
  params.require(:pet).permit(:name, :breed, :color, :weight, :category, :observations, :size, :photo, :photo_cache)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]

  def edit

  end

  def show
    @pending_pethome_bookings = []
    current_user.pethomes.each do |pethome|
      @pending_pethome_bookings << pethome.bookings.where(status: "pending")
    end
    @pending_pethome_bookings.flatten!

    @approved_pethome_bookings = []
    current_user.pethomes.each do |pethome|
      @approved_pethome_bookings << pethome.bookings.where(status: "approved")
    end
    @approved_pethome_bookings.flatten!



    @pending_my_bookings = current_user.bookings.where(status: "pending")
    @approved_my_bookings = current_user.bookings.where(status: "approved")
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        # format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

    def set_user
      @user = current_user
    end

    def user_params
      params.fetch(:user, {})
      params.require(:user).permit(:first_name, :last_name, :email, :photo, :photo_cache)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [@pethome, Booking.new] do |f| %>
  <%= f.input :starting_date %>
  <%= f.input :ending_date %>
  <%# f.input :photo_cache, as: :hidden %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/bookings/destroy.html.erb
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/show.html.erb
<h1>Bookings#show</h1>
<p>Find me in app/views/bookings/show.html.erb</p>

app/views/bookings/update.html.erb
<h1>Bookings#update</h1>
<p>Find me in app/views/bookings/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TOTO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
      <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pethomes/_form.html.erb
<%= simple_form_for(@pethome) do |f| %>
  <%= f.input :address %>
  <%= f.input :bedrooms %>
  <%= f.input :guests %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.input :observations %>
  <%# f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/pethomes/_pethome.html.erb
  <!-- test search form -->
  <%= simple_form_for root_path, :method => :get do |f| %>
    <%= f.input :search %>
    <%= f.button :submit %>
  <% end %>

app/views/pethomes/_search_form.html.erb
<div class="button">
  <%= simple_form_for "", url: pethomes_search_path, :method => :get do |f| %>
   <%= f.text_field :search, value: params[:search], placeholder: "Where?", class: "btn-medium" %>
    <%= f.submit "Search", class: "btn btn-primary btn-treehouse" %>
  <% end %>
</div>

app/views/pethomes/edit.html.erb
<h1>Pethomes#edit</h1>
<p>Find me in app/views/pethomes/edit.html.erb</p>

<%= render 'form' %>

app/views/pethomes/index.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/62379/pexels-photo-62379.jpeg');">

  <div class="banner-content">


    <h1>Welcome to DenStay</h1>
    <p> Find the perfect place to stay and lovely pets to take care of</p>


    <%= render 'search_form' %>

  </div>
</div>

app/views/pethomes/new.html.erb
<h1>Create a new pethome</h1>
<p></p>

<%= render 'form' %>

app/views/pethomes/search.html.erb
<br>
<div class="text-center">
  <%= render 'search_form' %>
</div>


<div class="row">
  <% @pethomes.each do |pethome| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(250,250,250,0.3),rgba(250,250,250,0.2)), url('<%= pethome.pets.any? ? pethome.pets.first.photo_url : Pet.default_url  %>')">
        <div class="card-description">
          <h2><%= pethome.address %></h2>
        </div>
        <img class="card-user" src="<%= pethome.user.photo_url %>">
        <%= link_to "", pethome, class: "card-link" %>
      </div>

    </div>
  <% end %>
</div>

app/views/pethomes/show.html.erb
<br>
<div class="row text-center">

  <div class="col-xs-12 col-md-4 text-left">
    <p><b>Address:</b> <%= @pethome.address %></p>
    <p><b>Number of Bedrooms:</b> <%= @pethome.bedrooms %>
    </p>
    <p><b>Maximum Guests:</b> <%= @pethome.guests %>
    </p>

    <p><%= @pethome.observations %>
    </p>
  </div>
  <div class="col-xs-12 col-md-4">
    <p><%= cl_image_tag @pethome.photo, width: 300 %></p>
  </div>
  <div class="col-xs-12 col-md-4">
    <p><%= cl_image_tag @pethome.user.photo, width: 100 %></p>
    <p><%= @pethome.user.first_name %> <%= @pethome.user.last_name %>
    </p>
  </div>
</div>

<h3>Pets</h3>

<% if @pethome.user == current_user %>
  <%= render "pets/form" %>
<% end %>

<% @pethome.pets.each do |pet| %>

  <p><%= cl_image_tag pet.photo, width: 50 %></p>

  <p><%= pet.name %></p>
<% end %>

<%= render "bookings/form" %>

app/views/pets/_form.html.erb
<%= simple_form_for [@pethome, @pet] do |f| %>
  <%= f.input :name %>
  <%= f.input :category %>
  <%= f.input :breed %>
  <%= f.input :weight %>
  <%= f.input :size %>
  <%= f.input :color %>
  <%= f.input :observations %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%# f.input :picture %>
  <%= f.submit "add pet", class: "btn btn-primary" %>
<% end %>

app/views/pets/create.html.erb
<h1>Pets#create</h1>
<p>Find me in app/views/pets/create.html.erb</p>

app/views/pets/new.html.erb
<h1>Create a new pet profile</h1>
<p>Find me in app/views/pets/new.html.erb</p>
<%= render 'form' %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="goog-te-gadget">
    <div id="google_translate_element"></div><script type="text/javascript">
      function googleTranslateElementInit() {
        new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
      }
    </script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    <style>
      div#google_translate_element div.goog-te-gadget-simple{background-color:#4ED99C;}
      div#google_translate_element div.goog-te-gadget-simple{border-radius: 20px;}
      div#google_translate_element div.goog-te-gadget-simple a.goog-te-menu-value span{color:yellow}
      div#google_translate_element div.goog-te-gadget-simple a.goog-te-menu-value span:hover{color:#fff}
    </style>​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​​
  </div>
  <div class="footer-copyright">
    This footer is made with by WeeRun Team <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "https://s-media-cache-ak0.pinimg.com/736x/0a/e1/5e/0ae15e66f2be1672974f3e3d86c52e86--font-design-cat-logo-design.jpg" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
    <!--   <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %> -->
      <%= link_to "New Pet Home", new_pethome_path, class: "navbar-wagon-item navbar-wagon-link" %>


      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo_url ? current_user.photo_url : "https://static.pexels.com/photos/4618/man-person-hat-fur.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to account_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!-- <div class="image_dog" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://static.pexels.com/photos/257570/pexels-photo-257570.jpeg'); background:fill"> -->
<center>
<h2>Welcome <%= current_user.first_name %></h1>

<%= link_to 'Edit', edit_user_registration_path %>
<%= link_to 'Back', account_path %>


<h3>Pending booking requests</h3>
<table class="booking_style">
<thead>
  <th>Reference</th>
  <th>Pethome</th>
  <th>From</th>
  <th>To</th>
  <th>Status</th>
</thead>

<tbody>
  <% @pending_my_bookings.each do |booking| %>
    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.pethome_id %></td>
      <td><%= booking.starting_date %></td>
      <td><%= booking.ending_date %></td>
      <td><%= booking.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<h3>Approved booking requests</h3>
<table class="booking_style">
<thead>
  <th>Reference</th>
  <th>Pethome</th>
  <th>From</th>
  <th>To</th>
  <th>Status</th>
</thead>

  <% @approved_my_bookings.each do |booking| %>
    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.pethome_id %></td>
      <td><%= booking.starting_date %></td>
      <td><%= booking.ending_date %></td>
      <td><%= booking.status %></td>
    </tr>
  <% end %>
</table>


<h3>Pending pethome bookings</h3>
<table class="booking_style">
<thead>
  <th>Reference</th>
  <th>Pethome</th>
  <th>From</th>
  <th>To</th>
  <th>Status</th>
</thead>

  <% @pending_pethome_bookings.each do |booking| %>
    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.pethome_id %></td>
      <td><%= booking.starting_date %></td>
      <td><%= booking.ending_date %></td>
      <td><%= booking.status %></td>
      <td><%= link_to  "approve", "bookings/#{booking.id}/approve", class: "btn btn-success", method: "patch" %></td>
    </tr>
  <% end %>
</table>


<h3>Approved pethome bookings</h3>
<table class="booking_style">
<thead>
  <th>Reference</th>
  <th>Pethome</th>
  <th>From</th>
  <th>To</th>
  <th>Status</th>
</thead>
  <% @approved_pethome_bookings.each do |booking| %>
    <tr>
      <td><%= booking.id %></td>
      <td><%= booking.pethome_id %></td>
      <td><%= booking.starting_date %></td>
      <td><%= booking.ending_date %></td>
      <td><%= booking.status %></td>
    </tr>
  <% end %>
</table>
</center>
<!-- </div> -->
<!-- create_table "users", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer "sign_in_count", default: 0, null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet "current_sign_in_ip"
    t.inet "last_sign_in_ip"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.string "picture"
    t.string "first_name"
    t.string "last_name"
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end
 -->